dist: focal
os: linux

language: node_js
node_js: "12"


#Normal node build 
# matrix:
#   include:
#     - arch: amd64
#       os: linux

#     - arch: s390x
#       os: linux

#Docker build for alpine and ubi8
jobs:
  include: 
    - stage: Linting 
      arch: amd64
      os: linux
      env: STEP=LINT
      install: npm install eslint@4.7.x
      script: 'npm run lint && npm run lint_tests'
      addons:
        apt:
          packages: # avoid installing packages
    - stage: Node Build
      arch: amd64
      os: linux
    - name: Node Build
      arch: s390x
      os: linux
    - stage: Docker Build
      name: alpine
      arch: amd64
      os: linux
      script: echo "Alpine job runs here"
    - 
      arch: s390x
      os: linux
      script: echo "Alpine job runs here"
    - stage: Docker build
      name: ubi8
      arch: amd64
      os: linux
      script: echo "ubi8 job runs here"
    - 
      arch: s390x
      os: linux
      script: echo "ubi8 job runs here"


before_script:
  - echo "Check for Lint"

script:
  - echo "Node build steps"
