# Che-Theia workflow
# matrix jobs with alpine and ubi8

dist: focal
os: linux
cache: yarn
git:
  depth: false 

language: node_js
node_js: "12"

install: skip
#Normal node build 
# matrix:
#   include:
#     - arch: amd64
#       os: linux

#     - arch: s390x
#       os: linux

#Docker build for alpine and ubi8
jobs:
  include: 
    - stage: Linting 
      arch: amd64
      os: linux
      env: STEP=LINT
      install: npm install eslint@4.7.x lerna
      script: echo "Lintline step"
      addons:
        apt:
          packages: # avoid installing packages
    - stage: Node Build
      arch: amd64
      os: linux
      script: yarn
    #- name: Node Build #name is needed to be included everywhere or else yarn test is executed(default behaviour) 
    #  arch: arm64
    #  os: linux
    #  script: yarn
    #- name: Node Build
    #  arch: ppc64le
    #  os: linux
    #  script: yarn
    - name: Node Build
      arch: s390x
      os: linux
      script: yarn
    - stage: Docker Build
      name: alpine 
      arch: amd64
      os: linux
      script: 
      - echo "Alpine job runs here"
      - docker image prune -a -f
      - docker pull --cache-from quay.io/eclipse/che-theia-dev:next
      - docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
      - ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine
    #- 
    #  arch: arm64
    #  os: linux
    #  script: 
    #  - echo "Alpine job runs here"
    #  - docker image prune -a -f
    #  - docker pull quay.io/eclipse/che-theia-dev:next
    #  - docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
    #  - ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine
    #- 
    #  arch: ppc64le
    #  os: linux
    #  script: 
    #  - echo "Alpine job runs here"
    #  - docker image prune -a -f
    #  - docker pull quay.io/eclipse/che-theia-dev:next
    #  - docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
    #  - ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine
    - 
      arch: s390x
      os: linux
      script: 
      - echo "Alpine job runs here"
      - docker image prune -a -f
      - docker pull --cache-from quay.io/eclipse/che-theia-dev:next
      - docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
      - ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine
    - stage: Docker build
      name: ubi8
      arch: amd64
      os: linux
      script: 
      - echo "ubi8 job runs here"
      - docker image prune -a -f
      - docker pull --cache-from quay.io/eclipse/che-theia-dev:next
      - docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
      - ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.ubi8
    # - 
    #   arch: arm64
    #   os: linux
    #   script: 
    #   - echo "ubi8 job runs here"
    #   - docker image prune -a -f
    #   - docker pull quay.io/eclipse/che-theia-dev:next
    #   - docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
    #   - ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.ubi8
    # - 
    #   arch: ppc64le
    #   os: linux
    #   script: 
    #   - echo "ubi8 job runs here"
    #   - docker image prune -a -f
    #   - docker pull quay.io/eclipse/che-theia-dev:next
    #   - docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
    #   - ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.ubi8
    - 
      arch: s390x
      os: linux
      script: 
      - echo "ubi8 job runs here"
      - docker image prune -a -f
      - docker pull --cache-from quay.io/eclipse/che-theia-dev:next
      - docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
      - ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.ubi8


before_script:
  - echo "Check for Lint"

script:
  - echo "Node build steps"
  
