dist: focal

language: node_js
node_js: "12"

matrix:
  include:
    - arch: amd64
      os: linux
    - arch: s390x
      os: linux

before_script:
  - echo "Check for Lint"

script:
  -echo "Node build steps"
