branches:
  only:
  - travis
  
language: node_js
node_js:
  - 12
  
services:
  - docker
env:
  global:
    - NODE_VERSION="12"
    - CDN_PREFIX: https://static.developers.redhat.com/che/theia_artifacts/
    - MONACO_CDN_PREFIX: https://cdn.jsdelivr.net/npm/
  matrix: # targets for linux
    - DIST=alpine
    - DIST=ubi8
matrix:
  include:
    - os: linux
      language: node_js
      node_js: "12"
      arch:
      - s390x
      - stage: Build and Test Coverage
      script:
      - | 
       if [ "$TRAVIS_PULL_REQUEST" != "true" ] ;then
        #yarn
        docker image prune -a -f
        docker pull quay.io/eclipse/che-theia-dev:next
        docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
        echo ${DIST}
       fi
    - os: linux
      language: node_js
      node_js: "12"
      arch:
      - amd64
      - stage: Build
      script:
      - | 
       if [ "$TRAVIS_PULL_REQUEST" != "true" ] ;then
         #yarn
         docker image prune -a -f
         docker pull quay.io/eclipse/che-theia-dev:next
         docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
         echo ${DIST}
         #./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.${DIST}
       fi
       if [ "$TRAVIS_PULL_REQUEST" != "false" ] ;then
         # Build image
         docker image prune -a -f 
         echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
         docker login quay.io -u="$QUAY_USERNAME " -p="$QUAY_PASSWORD"
      #./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine 
      #- printf "//registry.npmjs.org/:_authToken=${{ secrets.CHE_NPM_AUTH_TOKEN }}\n" >> ~/.npmrc
      #- yarn publish:next
       fi
