dist: focal
os: linux

language: node_js
node_js: "12"

install: echo "Skip initial yarn --frozen=lockfile step" 
#Docker build for alpine and ubi8
jobs:
  include: 
    - stage: Linting 
      arch: amd64
      os: linux
      env: STEP=LINT
      install: npm install eslint@4.7.x lerna
      script: echo "Lintline step"
      addons:
        apt:
          packages: # avoid installing packages
    - stage: Node Build
      arch: amd64
      os: linux
      script: yarn
    - 
      arch: arm64
      os: linux
      script: yarn
    - 
      arch: ppc64le
      os: linux
      script: yarn
    - 
      arch: s390x
      os: linux
      script: yarn
    - stage: Docker Build
      name: alpine
      arch: amd64
      os: linux
      script: 
      - echo "Alpine job runs here"
      - echo ${name}
    - 
      arch: arm64
      os: linux
      script: echo "Alpine job runs here"      
    - 
      arch: ppc64le
      os: linux
      script: echo "Alpine job runs here"      
    - 
      arch: s390x
      os: linux
      script: echo "Alpine job runs here"
    - stage: Docker build
      name: ubi8
      arch: amd64
      os: linux
      script: echo "ubi8 job runs here"
    - 
      arch: arm64
      os: linux
      script: echo "ubi8 job runs here"
    - 
      arch: ppc64le
      os: linux
      script: echo "ubi8 job runs here"
    - 
      arch: s390x
      os: linux
      script: echo "ubi8 job runs here"
