# Che-Theia workflow
# matrix jobs with alpine and ubi8


dist: focal
os: linux
cache: yarn
git:
  depth: false 

language: node_js
node_js: "12"

before_install:
  - sudo apt-get update -qq && sudo apt-get install -y jq
    # Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # Log into Quay.io
  - docker login quay.io -u="$QUAY_USERNAME " -p="$QUAY_PASSWORD"

install: skip

stages:
  - name: PR Check
    if: type = pull_request  # To be chnged later to =pr, marked != for testing purpose
  - name: Build & Publish 'next'
    if: type = push AND branch = travis
  - name: Check a Theia branch
    if: type = api
  - name: Check existing refs/tags/ 
    if: type = api AND env(TAG) != "next"
  - name: Release
    if: type = api AND env(TAG) != "next"
  - name: Build and publish images
    if: type = api AND env(TAG) != "next"
          

env: 
  global:
  - THEIA_GITHUB_REPO=eclipse-theia/theia
  - THEIA_BRANCH=master
  - TAG=next
  - CDN_PREFIX=https://static.developers.redhat.com/che/theia_artifacts/
  - MONACO_CDN_PREFIX=https://cdn.jsdelivr.net/npm/
  - RECREATE_TAGS=false
  - pushToNpmJs=true


jobs:
  include: 
    - stage: PR Check
      name: Linting 
      arch: amd64
      env: STEP=LINT
      install: npm install eslint@4.7.x lerna
      script: echo "Lintline step"
    - &node-build
      name: Node Build
      arch: amd64
      script: yarn
    # - <<: *node-build
    #   name: Node Build on arm64 #name is needed to be included everywhere or else yarn test is executed(default behaviour) 
    #   arch: arm64
    - <<: *node-build
      name: Node Build on ppc64le
      arch: ppc64le
    - <<: *node-build
      name: Node Build on s390x
      arch: s390x
    - &docker-build-alpine
      name: Docker Build(Alpine)
      arch: amd64
      script: 
      - echo "Alpine Docker builds"
      - bash .travis/publish_multiarch.sh ${TRAVIS_CPU_ARCH} alpine
    # - <<: *docker-build-alpine
    #   arch: arm64
    - <<: *docker-build-alpine
      arch: ppc64le
    - <<: *docker-build-alpine
      arch: s390x
    - &docker-build-ubi8
      name: Docker build(ubi8)
      arch: amd64
      script: 
      - echo "ubi8 job runs here"
      - bash .travis/publish_multiarch.sh ${TRAVIS_CPU_ARCH} ubi8
    # - <<: *docker-build-ubi8
    #   arch: arm64
    - <<: *docker-build-ubi8
      arch: ppc64le
    - <<: *docker-build-ubi8
      arch: s390x

    - &build-and-push-next
      stage: Build & Publish 'next'
      arch: amd64
      script: 
      - docker image prune -a -f
      - ./build.sh ${TRAVIS_CPU_ARCH} --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine --push 
      #- printf "//registry.npmjs.org/:_authToken=${{ secrets.CHE_NPM_AUTH_TOKEN }}\n" >> ~/.npmrc
      #- yarn publish:next
    # - <<: *build-and-push-next
    #   arch: arm64
    - <<: *build-and-push-next
      arch: ppc64le
    - <<: *build-and-push-next
      arch: s390x
    - stage: Publish multiarch image with next tag
      if: branch = travis AND env(TAG) = "next"
      name: Publish multiarch image with next tag
      script: bash .travis/publish_multiarch.sh $TAG
    - stage: Publish packages to npmjs
      name: Publish packages to npmjs
      if: type = push AND branch = travis
      script: 
      - printf "//registry.npmjs.org/:_authToken=${CHE_NPM_AUTH_TOKEN}\n" >> ~/.npmrc
      - yarn publish:next

    - &check-a-theia-branch
      stage: Check a Theia branch
      arch: amd64
      language: node_js
      node_js: "12"
      before_install: npm i -g lerna
      script:
      - docker image prune -a -f
      - docker pull quay.io/prabhav/che-theia-dev:next
      - docker tag quay.io/prabhav/che-theia-dev:next prabhav/che-theia-dev:next
      - ./build.sh ${TRAVIS_CPU_ARCH} --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine --build-args:THEIA_GITHUB_REPO=${THEIA_GITHUB_REPO} --branch:${THEIA_BRANCH}
    # - <<: *check-a-theia-branch
    #   arch: arm64
    - <<: *check-a-theia-branch
      arch: ppc64le
    - <<: *check-a-theia-branch
      arch: s390x
    
    #Release Workflow
    - stage: Check existing tags
      name: Check existing tags
      if: type = api AND env(TAG) != "next"
      arch: amd64
      os: linux
      language: node_js
      node_js: "12"
      script:
      - |  
        set +e
        VERSION=${TAG}
        EXISTING_TAG=$(git ls-remote --exit-code origin refs/tags/${VERSION})
        if [[ -n ${EXISTING_TAG} ]]; then
          if [[ ${RECREATE_TAGS} == "true" ]]; then
            echo "[INFO] Removing tag for ${VERSION} version. New tag will be recreated during release."
            git push origin :$VERSION
          else
            echo "[ERROR] Cannot proceed with release - tag ${EXISTING_TAG} already exists."
            exit 1
          fi
        else
          echo "[INFO] No existing tags detected for $VERSION"
        fi
    - &prepare-release
      stage: Release Che Theia
      description: The version that is going to be released. Should be in format 7.y.z
      name: Prepare release and build images
      if: type = api AND env(TAG) != "next"
      arch: amd64
      os: linux
      script:
      - |  
        export GITHUB_TOKEN=${CHE_BOT_GITHUB_TOKEN}
        export AKAMAI_CHE_AUTH=""
        ./make-release-sed.sh
        docker image prune -a -f
        ./build.sh  ${TRAVIS_CPU_ARCH} --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine --push 
    - <<: *prepare-release
      arch: arm64
    - <<: *prepare-release
      arch: ppc64le
    - <<: *prepare-release
      arch: s390x
    - stage: Publish multiarch image
      name: Publish multiarch image 
      if: type = api AND env(TAG) != "next" 
      script: 
      - bash .travis/publish_multiarch.sh $TAG

    - stage: Tag release
      name: Tag release and Notify
      if: type = api AND env(TAG) != "next"
      arch: amd64
      script:
      - |  
        git config --global user.name "Mykhailo Kuznietsov"
        git config --global user.email "mkuznets@redhat.com"
        bash make-release.sh --version $TAG --tag-release $NO_COMMIT

    - stage: Publish packages to npmjs
      if: ${pushToNpmJs} == true AND type = api AND env(TAG) != "next"
      name: Publish packages to npmjs
      script: 
      - printf "//registry.npmjs.org/:_authToken=${CHE_NPM_AUTH_TOKEN}\n" >> ~/.npmrc
      - yarn publish:next
      after_success:
       - |
         echo "{\"text\":\":white_check_mark: Che Theia ${{ github.event.inputs.version }} has been released: https://quay.io/eclipse/che-theia-dev:${{ github.event.inputs.version }} https://quay.io/eclipse/che-theia:${{ github.event.inputs.version }} https://quay.io/eclipse/che-theia-endpoint-runtime-binary:${{ github.event.inputs.version }} https://quay.io/eclipse/che-theia-vsix-installer:${{ github.event.inputs.version }}\"}" > mattermost.json
         echo mattermost.json
      after_failure:
       - |
         echo "{\"text\":\":no_entry_sign: Che Theia ${{ github.event.inputs.version }} release has failed: https://github.com/eclipse-che/che-theia/actions/workflows/release.yml\"}" > mattermost.json
         echo mattermost.json

  # Upload code coverage results to codecov.io, see https://github.com/codecov/codecov-bash for more information
  #- bash <(curl -s https://codecov.io/bash) 
