dist: focal

language: node_js
node_js: "12"

#Normal node build 
# matrix:
#   include:
#     - arch: amd64
#       os: linux

#     - arch: s390x
#       os: linux

#Docker build for alpine and ubi8
jobs:
  include: 
    - stage: Node Build
      arch: amd64
      os: linux
    - name: Node Build(ubi8)
      arch: s390x
      os: linux
    - stage: Docker Build(alpine)
      arch: amd64
      os: linux
      dist: alpine
      script: echo "Alpine job runs here"
    - name: Docker Build(ubi8)
      arch: amd64
      os: linux
      dist: ubi8
      script: echo "ubi8 job runs here"
    - stage: Docker Build(alpine-s390x)
      arch: s390x
      os: linux
      dist: alpine
      script: echo "Alpine job runs here"
    - name: Docker Build(ubi8-s390x)
      arch: s390x
      os: linux
      dist: ubi8
      script: echo "ubi8 job runs here"


before_script:
  - echo "Check for Lint"

script:
  - echo "Node build steps"
