# Che-Theia workflow
# matrix jobs with alpine and ubi8

branches:
  only:
  - travis

services:
  - docker

os: linux
dist: focal

jobs:
  include:
    - stage: CI
      name: linelint 
      script: echo "Lint check"
      
    - stage: CI
      name: node-build
      script: echo "Node build"
    
    - stage: CI
      name: docker-build
      script:
      - echo "Build on Matrix"
